// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBOj4YitCRZFJWFsBS6zLDwy08zyA3PHQk',
    appId: '1:115230536648:web:92a35b3b11deb04b7906fd',
    messagingSenderId: '115230536648',
    projectId: 'stunnzone-d3ea5',
    authDomain: 'stunnzone-d3ea5.firebaseapp.com',
    storageBucket: 'stunnzone-d3ea5.appspot.com',
    measurementId: 'G-B51NN0WV9B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCQAxYXPrzqgEBbyxQlvHZEb2pHvqdHMFI',
    appId: '1:115230536648:android:0b3b6bfab5864f1b7906fd',
    messagingSenderId: '115230536648',
    projectId: 'stunnzone-d3ea5',
    storageBucket: 'stunnzone-d3ea5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB4o68I0oetgU-mGQwyQA9lVVIcj2l4cis',
    appId: '1:115230536648:ios:9e3a3e4aaebb25d37906fd',
    messagingSenderId: '115230536648',
    projectId: 'stunnzone-d3ea5',
    storageBucket: 'stunnzone-d3ea5.appspot.com',
    androidClientId: '115230536648-dsqmui0idpubfociefd8233ibjpkv513.apps.googleusercontent.com',
    iosBundleId: 'com.example.shopnow',
  );
}
